theme = "awesome-identity"
baseURL = "https://geetoca.com"
title = "$ whoami"

## Profile Configurations
[params.profile]
  portrait = "/images/avatar.png"
  firstname = "Gee"
  lastname = "Toca"
  title = "Cyber Security Enthusiast"
  bio = """I've been curious to find out how technology works since I was a kid. Currently, I am an IT professional and cyber security enthusiast with a strong interest in Ethical Hacking. In my free time, I search for vulnerabilities on the bug bounty platform <a href="https://hackerone.com/geej">hackerone</a> and <a href="https://bugcrowd.com/geej">bugcrowd</a>."""

[params.contacts]
  github = "geej-t"
  linkedin = "geej-t"
  twitter = "notgeej"
  medium = "@gee.toca"

## Footer Configurations
[params.footer]
  copyright = "© 2024 Gee. [Some rights reserved.](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true

